title: Learning GitHub
author: My GitHub User
email: email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Learning how to use GitHub.
theme: minima

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
